### ISSUE TITLE
HTTP handler with custom URL paths

### ISSUE THREAD

**Issue by libesz** [ContainerSSH/auth#35]
## Describe the bug

Following the README I want to implement an auth+config server, where I use the standard Go http server implementation, as suggested:
```
func main() {
    logger := log.New(...)
    httpHandler := auth.NewHandler(&myHandler{}, logger)
    http.HandleFunc("/auth", httpHandler)
    http.ListenAndServe(":8090", nil)
}
```
The SSH server configuration allows this path setting and correctly sends the requests like:
```
{"timestamp":"2021-10-17T20:22:24Z","level":"debug","code":"HTTP_CLIENT_REQUEST","message":"HTTP POST request to http://127.0.0.1:8090/auth/password","details":{"endpoint":"http://127.0.0.1:8090/auth","method":"POST","module":"auth","path":"/password"}}
```
If I am not mistaken, this does not deliver the requests. The problem is that the handler implementation is explicitly expecting the `/password` or `/pubkey` paths, while not tolerating any prefixes. Ref to [code](https://github.com/ContainerSSH/auth/blob/main/handler_impl.go#L17).

## To Reproduce

If you can please provide the steps to reproduce the issue.
0. Implement auth server using standard Go http server where the auth handler is not using `/`, but some prefixes, like in README: `/auth`
1. Run ContainerSSH with these parameters:
```
ssh:
  banner: "Welcome to ContainerSSH!\n"
  hostkeys:
    - /var/secrets/ssh_host_rsa_key
log:
  level: debug
auth:
  url: "http://149.81.84.178:8090/auth"
configserver:
  url: "http://149.81.84.178:8090/config"
backend: docker
docker:
  connection:
    host: unix:///var/run/docker.sock
```
2. Try to log in. Check SSH server logs

## Expected behavior

I would expect that such URL path prefixes should work.

## Version

If you can please insert the output of `containerssh --version` here:
latest

## Workaround
If I wrap the auth handler and cheat with the URL path, it works as expected.
```
	authHandler := auth.NewHandler(&myHandler{}, logger)
	http.HandleFunc("/", func(rw http.ResponseWriter, r *http.Request) {
		if r.Method == "POST" {
			isAuth := false
			if r.URL.Path == "/auth/password" {
				r.URL.Path = "/password"
				isAuth = true
			}
			if r.URL.Path == "/auth/pubkey" {
				isAuth = true
				r.URL.Path = "/pubkey"
			}
			if isAuth {
				authHandler.ServeHTTP(rw, r)
				return
			}
		}
		rw.WriteHeader(http.StatusInternalServerError)
	})
```
